/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoAdminRole;

import Business.BusinessModel;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nidhitiwari
 */
public class NgoAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    BusinessModel business;
    UserAccount account;
    /**
     * Creates new form NgoAdminWorkAreaJPanel
     */
    public NgoAdminWorkAreaJPanel(JPanel userProcessContainer,
            UserAccount account,
            BusinessModel business
            ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        lblNgoName.setText(account.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        lblNgoName = new javax.swing.JLabel();
        lblWarehouseAdminRole = new javax.swing.JLabel();
        btnManageWarehouseInfo = new javax.swing.JButton();
        btnManageDiscardedItems = new javax.swing.JButton();

        lblEnterprise.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblEnterprise.setText("NGO");

        lblNgoName.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lblNgoName.setText("<value>");

        lblWarehouseAdminRole.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWarehouseAdminRole.setText("My Work Area -NGO Adminstrative Role");

        btnManageWarehouseInfo.setBackground(new java.awt.Color(0, 153, 255));
        btnManageWarehouseInfo.setText("Manage NGO Info");
        btnManageWarehouseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWarehouseInfoActionPerformed(evt);
            }
        });

        btnManageDiscardedItems.setBackground(new java.awt.Color(0, 153, 255));
        btnManageDiscardedItems.setText("Manage Orgs");
        btnManageDiscardedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDiscardedItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lblNgoName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageDiscardedItems, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(btnManageWarehouseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblWarehouseAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblWarehouseAdminRole)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgoName)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnManageDiscardedItems)
                .addGap(18, 18, 18)
                .addComponent(btnManageWarehouseInfo)
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWarehouseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWarehouseInfoActionPerformed
        // TODO add your handling code here:
        ManageNGOInfo manageInfo=new ManageNGOInfo(userProcessContainer,account,business);
        userProcessContainer.add("Manage NGO",manageInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageWarehouseInfoActionPerformed

    private void btnManageDiscardedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDiscardedItemsActionPerformed
        ManageOrg manageOrg=new ManageOrg(userProcessContainer,account,business);
        userProcessContainer.add("Manage Organizations",manageOrg);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDiscardedItemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDiscardedItems;
    private javax.swing.JButton btnManageWarehouseInfo;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblNgoName;
    private javax.swing.JLabel lblWarehouseAdminRole;
    // End of variables declaration//GEN-END:variables
}
