/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WarehouseAdminRole;

import Business.BusinessModel;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nidhitiwari
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    BusinessModel business;
    UserAccount account;
    
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,
            UserAccount account,
            BusinessModel business
            ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = business;
        lblWarehouseName.setText(account.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarehouseAdminRole = new javax.swing.JLabel();
        btnManageWarehouseInfo = new javax.swing.JButton();
        btnManageDiscardedItems = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        lblWarehouseName = new javax.swing.JLabel();

        lblWarehouseAdminRole.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        lblWarehouseAdminRole.setText("My Work Area -Warehouse Adminstrative Role");

        btnManageWarehouseInfo.setBackground(new java.awt.Color(0, 153, 255));
        btnManageWarehouseInfo.setText("Manage Warehouse Info");
        btnManageWarehouseInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageWarehouseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWarehouseInfoActionPerformed(evt);
            }
        });

        btnManageDiscardedItems.setBackground(new java.awt.Color(0, 153, 255));
        btnManageDiscardedItems.setText("Manage Discarded Items");
        btnManageDiscardedItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageDiscardedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDiscardedItemsActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEnterprise.setText("Warehouse:");

        lblWarehouseName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWarehouseName.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnManageDiscardedItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnManageWarehouseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(308, 308, 308))
                            .addComponent(lblWarehouseAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarehouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblWarehouseAdminRole)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWarehouseName)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnManageDiscardedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnManageWarehouseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWarehouseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWarehouseInfoActionPerformed
        // TODO add your handling code here:
        ManageWarehouseInfo manageInfo=new ManageWarehouseInfo(userProcessContainer,account,business);
        userProcessContainer.add("Manage Warehouse",manageInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageWarehouseInfoActionPerformed

    private void btnManageDiscardedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDiscardedItemsActionPerformed
        ManageDiscardedItems manageItem=new ManageDiscardedItems(userProcessContainer,account,business);
        userProcessContainer.add("Manage Discarded Items",manageItem);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDiscardedItemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDiscardedItems;
    private javax.swing.JButton btnManageWarehouseInfo;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblWarehouseAdminRole;
    private javax.swing.JLabel lblWarehouseName;
    // End of variables declaration//GEN-END:variables
}
